# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-18 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='diasHabiles',
            field=models.IntegerField(default=5, verbose_name='Cantidad de dias Habiles en la Semana'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=5, verbose_name='Duracion del Sprint'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN EJECUCION', 'En Ejecucion'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaFinEstimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion Estimada'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaInicioEstimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Estimada'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='scrum_master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master_proyecto_creador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='MyAwesomeProject', help_text='El nombre del proyecto (debe ser único en el sistema)', max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
