# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-21 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0002_auto_20190318_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('horasTrabajadas', models.IntegerField(verbose_name='Horas Trabajadas')),
                ('estado', models.IntegerField(verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=20, verbose_name='Campo Personalizado')),
                ('tipoDeDato', models.CharField(max_length=7, verbose_name='Tipo de Dato')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=100, verbose_name='RUC')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre y Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('orden', models.IntegerField(verbose_name='Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('estado', models.IntegerField(verbose_name='Estado')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('miembros', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionCorta', models.CharField(max_length=50, verbose_name='Descripcion Corta')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('criterioAceptacion', models.CharField(max_length=100, verbose_name='Criterio de Aceptacion')),
                ('valorNegocio', models.IntegerField(verbose_name='Valor de Negocio')),
                ('valorTecnico', models.IntegerField(verbose_name='Valor Tecnico')),
                ('prioridad', models.IntegerField(verbose_name='Prioridad')),
                ('tiempoPlanificado', models.IntegerField(verbose_name='Tiempo Planificado')),
                ('tiempoEjecutado', models.IntegerField(verbose_name='Tiempo Ejecutado')),
                ('estadoSistema', models.IntegerField(verbose_name='Estado en el Sistema')),
                ('faseActual', models.IntegerField(verbose_name='Fase actual en el flujo')),
                ('estadoFaseActual', models.IntegerField(verbose_name='Estado actual en la fase actual del flujo')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Flujo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TipoUS')),
            ],
        ),
        migrations.CreateModel(
            name='UserStorySprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Sprint')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.UserStory')),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampoPersonalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor del Campo Personalizado')),
                ('campoPersonalizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.CampoPersonalizado')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.UserStory')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Flujo'),
        ),
        migrations.AddField(
            model_name='campopersonalizado',
            name='tipoUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TipoUS'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Fase'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='us_sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.UserStorySprint'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_cliente', to='proyecto.Cliente'),
        ),
    ]
