# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20190323_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='us_sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.UserStorySprint'),
        ),
    ]
