# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-26 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20190321_1602'),
        ('proyecto', '0004_miembroproyecto_roles'),
    ]

    operations = [
    ]
