# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-28 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_rolproyecto_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolproyecto',
            unique_together=set([('nombre', 'proyecto')]),
        ),
    ]
