# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-28 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20190328_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroproyecto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
