# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-29 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20190328_2337'),
        ('proyecto', '0008_auto_20190328_1410'),
    ]

    operations = [
    ]
