# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-29 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_merge_20190329_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('view_cliente', 'Can view clientes'),)},
        ),
    ]
