# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-30 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20190329_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('view_proyecto', 'Tiene permiso de lectura de Proyecto'),)},
        ),
    ]
