# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_auto_20190329_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=15, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
    ]
