# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20190409_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
