# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20190411_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('add_usuario', 'Agregar Usuario'), ('change_usuario', 'Modificar Usuario'), ('delete_usuario', 'Eliminar Usuario')),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='campopersonalizado',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'default_permissions': (), 'permissions': (('add_cliente', 'Agregar Cliente'), ('change_cliente', 'Modificar Cliente'), ('delete_cliente', 'Eliminar Cliente'))},
        ),
        migrations.AlterModelOptions(
            name='fase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='flujo',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='miembroproyecto',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'permissions': (('add_proyecto', 'Agregar Proyecto'), ('change_proyecto', 'Modificar Proyecto'), ('delete_proyecto', 'Eliminar Proyecto'), ('add_rolproyecto', 'Agregar Rol al Proyecto'), ('change_rolproyecto', 'Modificar Rol del Proyecto'), ('delete_rolproyecto', 'Eliminar Rol del Proyecto'), ('add_miembroproyecto', 'Agregar Miembro al Proyecto'), ('change_miembroproyecto', 'Modificar Miembro del Proyecto'), ('delete_miembroproyecto', 'Eliminar Miembro del Proyecto'), ('add_tipous', 'Agregar Tipo User Story al Proyecto'), ('change_tipous', 'Modificar Tipo User Story del Proyecto'), ('delete_tipous', 'Eliminar Tipo US del Proyecto'), ('add_flujo', 'Agregar Flujo al Proyecto'), ('change_flujo', 'Modificar Flujo del Proyecto'), ('delete_flujo', 'Eliminar Flujo del Proyecto'), ('add_us', 'Agregar User Story al Proyecto'), ('change_us', 'Modificar User Story del Proyecto'), ('delete_us', 'Eliminar User Story del Proyecto'), ('administrar_sprint', 'Administrar Sprints del Proyecto'), ('desarrollador_proyecto', 'Realizar US'))},
        ),
        migrations.AlterModelOptions(
            name='roladministrativo',
            options={'default_permissions': (), 'permissions': (('add_roladministrativo', 'Agregar Rol Administrativo'), ('change_roladministrativo', 'Modificar Rol Administrativo'), ('delete_roladministrativo', 'Eliminar Rol Administrativo'))},
        ),
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='tipous',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='userstorysprint',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='valorcampopersonalizado',
            options={'default_permissions': ()},
        ),
    ]
