# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-13 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0014_auto_20190411_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario_creador',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario_modificador',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='scrum_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master_proyecto_creador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
