# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20190413_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN EJECUCION', 'En Ejecucion'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='campo',
            field=models.CharField(choices=[('NUMERO', 'Numero'), ('STRING', 'String')], default='STRING', max_length=20, verbose_name='Campo Personalizado'),
        ),
        migrations.AlterUniqueTogether(
            name='campopersonalizado',
            unique_together=set([('tipoUS', 'campo')]),
        ),
        migrations.AlterUniqueTogether(
            name='valorcampopersonalizado',
            unique_together=set([('us', 'campoPersonalizado')]),
        ),
    ]
