# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20190414_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='fase',
            name='orden',
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together=set([('flujo', 'nombre')]),
        ),
    ]
