# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-14 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_auto_20190414_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=5, help_text='La duracion del sprint debe estar en semanas', verbose_name='Duracion del Sprint'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='scrum_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master_proyecto_creador', to=settings.AUTH_USER_MODEL, verbose_name='Scrum Master'),
        ),
    ]
