# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_auto_20190414_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='descripcionCorta',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='estadoFaseActual',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='estadoSistema',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='faseActual',
        ),
        migrations.AddField(
            model_name='userstory',
            name='estadoFase',
            field=models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done')], max_length=10, null=True, verbose_name='estado en la fase'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='estadoProyecto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INICIADO', 'Iniciado'), ('CANCELADO', 'Cancelado'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=15, verbose_name='estado del US en el proyecto'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Fase', verbose_name='fase en la que se encuentra el US'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(default='user story no válido', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstory',
            name='criterioAceptacion',
            field=models.CharField(help_text='Aquí podría especificar las características del producto resultado de las actividades de un US, para que el US sea aceptado', max_length=500, verbose_name='criterio de aceptación'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Flujo', verbose_name='flujo que debe seguir el US'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'No Importante'), (1, 'Muy Baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy Alta'), (6, 'Super Importante')], default=3),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEjecutado',
            field=models.IntegerField(verbose_name='tiempo ejecutado (en horas)'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoPlanificado',
            field=models.IntegerField(help_text='Especifique cuántas horas cree que le llevará a una persona terminar este US', verbose_name='tiempo planificado (en horas)'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorNegocio',
            field=models.IntegerField(default=1, verbose_name='valor de negocio'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorTecnico',
            field=models.IntegerField(default=1, verbose_name='valor técnico'),
        ),
    ]
