# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_auto_20190414_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='orden',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together=set([('flujo', 'orden')]),
        ),
    ]
