# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-15 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_auto_20190414_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together=set([('flujo', 'orden'), ('flujo', 'nombre')]),
        ),
    ]
