# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-15 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_auto_20190414_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='orden',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(default=0, help_text='Este valor nos dice cuantas horas de trabajo disponible hay en el sprint', verbose_name='capacidad del sprint (en horas)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='duracion',
            field=models.IntegerField(verbose_name='duración del sprint (en semanas)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_EJECUCION', 'En Ejecución'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='miembros',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='nombre',
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together=set([('proyecto', 'orden')]),
        ),
    ]
