# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-16 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0024_auto_20190415_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorysprint',
            name='asignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.MiembroSprint'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userstorysprint',
            name='miembro',
        ),
        migrations.AlterUniqueTogether(
            name='userstorysprint',
            unique_together=set([('us', 'sprint')]),
        ),
    ]
