# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0026_auto_20190416_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrosprint',
            name='horasAsignadas',
            field=models.IntegerField(verbose_name='Horas por día asignadas al miembro'),
        ),
    ]
