# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0027_auto_20190417_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
