# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-21 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0028_rolproyecto_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='describa en qué consistirá el proyecto', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='diasHabiles',
            field=models.IntegerField(default=5, help_text='cantidad de días hábiles en la semana', verbose_name='días hábiles'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=4, help_text='duración estimada para los sprints (en semanas)', verbose_name='duración del sprint'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN EJECUCION', 'En Ejecucion'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFinEstimada',
            field=models.DateField(blank=True, help_text='fecha de finalización estimada', null=True, verbose_name='finalización'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicioEstimada',
            field=models.DateField(blank=True, help_text='fecha de inicio estimada', null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='My Awesome Project', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='scrum_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='scrum master'),
        ),
    ]
