# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0029_auto_20190421_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseDeFlujoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Fase')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='fasedeflujoproyecto',
            unique_together=set([('proyecto', 'fase')]),
        ),
    ]
