# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0032_auto_20190424_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='criterioAceptacion',
        ),
        migrations.AddField(
            model_name='userstory',
            name='criteriosAceptacion',
            field=models.TextField(default='abc', help_text='condiciones para que el US sea aceptado como terminado', verbose_name='criterios de aceptación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(verbose_name='descripción'),
        ),
    ]
