# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-24 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_auto_20190424_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together=set([('proyecto', 'nombre')]),
        ),
    ]
