# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0034_auto_20190424_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='priorizacion',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estadoProyecto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_SPRINT', 'En Sprint'), ('CANCELADO', 'Cancelado'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=15, verbose_name='estado del US en el proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorNegocio',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3, verbose_name='valor de negocio'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorTecnico',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3, verbose_name='valor técnico'),
        ),
    ]
