# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0035_auto_20190424_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='estadoProyecto',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Sprint'), (3, 'No Terminado'), (4, 'Cancelado'), (5, 'Terminado')], default=1, verbose_name='estado del US en el proyecto'),
        ),
    ]
