# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 19:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0036_auto_20190424_2142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorcampopersonalizado',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='valorcampopersonalizado',
            name='campoPersonalizado',
        ),
        migrations.RemoveField(
            model_name='valorcampopersonalizado',
            name='us',
        ),
        migrations.AddField(
            model_name='userstory',
            name='valoresCPs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=proyecto.models.default_vals),
        ),
        migrations.DeleteModel(
            name='ValorCampoPersonalizado',
        ),
    ]
