# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0037_auto_20190425_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrosprint',
            name='horasAsignadas',
            field=models.PositiveIntegerField(verbose_name='Horas por día asignadas al miembro'),
        ),
    ]
