# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0038_auto_20190425_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorysprint',
            name='asignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='proyecto.MiembroSprint'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horasTrabajadas',
            field=models.PositiveIntegerField(default=0, verbose_name='horas trabajadas'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='cantidadFases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='diasHabiles',
            field=models.PositiveIntegerField(default=5, help_text='cantidad de días hábiles en la semana', verbose_name='días hábiles'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.PositiveIntegerField(default=4, help_text='duración estimada para los sprints (en semanas)', verbose_name='duración del sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, help_text='Este valor nos dice cuantas horas de trabajo disponible hay en el sprint', verbose_name='capacidad del sprint (en horas)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='duracion',
            field=models.PositiveIntegerField(verbose_name='duración del sprint (en semanas)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.PositiveIntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoPlanificado',
            field=models.PositiveIntegerField(help_text='cuántas horas cree que le llevará a una persona terminar este US', verbose_name='tiempo planificado (en horas)'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorNegocio',
            field=models.PositiveIntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3, verbose_name='valor de negocio'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valorTecnico',
            field=models.PositiveIntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Normal'), (4, 'Alto'), (5, 'Muy Alto')], default=3, verbose_name='valor técnico'),
        ),
    ]
