# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0039_auto_20190425_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='miembrosprint',
            name='horasAsignadas',
            field=models.PositiveIntegerField(validators=[proyecto.models.validar_mayor_a_cero], verbose_name='Horas por día asignadas al miembro'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='diasHabiles',
            field=models.PositiveIntegerField(default=5, help_text='cantidad de días hábiles en la semana', validators=[proyecto.models.validar_mayor_a_cero], verbose_name='días hábiles'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.PositiveIntegerField(default=4, help_text='duración estimada para los sprints (en semanas)', validators=[proyecto.models.validar_mayor_a_cero], verbose_name='duración del sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='duracion',
            field=models.PositiveIntegerField(validators=[proyecto.models.validar_mayor_a_cero], verbose_name='duración del sprint (en semanas)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='orden',
            field=models.PositiveIntegerField(validators=[proyecto.models.validar_mayor_a_cero]),
        ),
    ]
