# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0041_auto_20190426_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='archivos_adjuntos',
            field=models.FileField(help_text='El archivo adjunto de la actividad', null=True, upload_to='archivos_adjuntos/'),
        ),
        migrations.AddField(
            model_name='userstorysprint',
            name='estado_fase_sprint',
            field=models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done')], help_text='Estado en el que se encuentra un user story en un sprint', max_length=10, null=True, verbose_name='estado en la fase'),
        ),
        migrations.AddField(
            model_name='userstorysprint',
            name='fase_sprint',
            field=models.ForeignKey(help_text='Fase en la que se encuentra un user story en un sprint', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Fase', verbose_name='fase en la que se encuentra el US'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.MiembroProyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estadoProyecto',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Sprint'), (3, 'No Terminado'), (4, 'Cancelado'), (5, 'Terminado'), (6, 'En Revision')], default=1, verbose_name='estado del US en el proyecto'),
        ),
    ]
