# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0042_auto_20190503_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='El orden de la fase dentro de su flujo correspondiente. Comienza desde cero'),
        ),
    ]
