# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0044_auto_20190504_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'default_permissions': ()},
        ),
        migrations.AddField(
            model_name='sprint',
            name='justificacion',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Justificacion'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='justificacion',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Justificacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='describa en qué consistirá el proyecto', null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN EJECUCION', 'En Ejecución'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, help_text='Este valor nos dice cuántas horas de trabajo disponible hay en el sprint', verbose_name='capacidad del sprint (en horas)'),
        ),
    ]
