# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0046_auto_20190506_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='archivos_adjuntos',
            new_name='archivoAdjunto',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaHora',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha y hora de registro'),
        ),
    ]
