# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0048_auto_20190508_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEjecutado',
            field=models.PositiveIntegerField(default=0, verbose_name='tiempo ejecutado (en horas)'),
        ),
    ]
