# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-17 13:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0050_auto_20190509_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='estadoProyecto',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Sprint'), (3, 'No Terminado'), (4, 'Cancelado'), (5, 'Terminado'), (6, 'En Revisión')], default=1, verbose_name='estado del US en el proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valoresCPs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=proyecto.models.default_vals),
        ),
    ]
