# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0052_auto_20190517_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='total_horas_planificadas',
            field=models.PositiveIntegerField(default=0, help_text='El total de las horas planificadas de todos los user stories en un sprint'),
        ),
    ]
