# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0052_auto_20190517_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstorysprint',
            name='prioridad_suprema',
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad_suprema',
            field=models.PositiveIntegerField(default=0, help_text='Campo que determina si un user story no culmino en un sprint anterior'),
        ),
    ]
