# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0054_sprint_total_horas_planificadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracion',
            field=models.PositiveIntegerField(default=1, validators=[proyecto.models.validar_mayor_a_cero], verbose_name='duración del sprint (en semanas)'),
        ),
    ]
