# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-24 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0056_auto_20190523_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horasTrabajadas',
            field=models.PositiveIntegerField(default=1, validators=[proyecto.models.validar_mayor_a_cero], verbose_name='horas trabajadas'),
        ),
    ]
