# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0057_auto_20190523_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='archivoAdjunto',
            field=models.FileField(blank=True, help_text='El archivo adjunto de la actividad', null=True, upload_to='proyecto.ArchivosActividad/bytes/filename/mimetype'),
        ),
    ]
