# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0059_auto_20190524_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorysprint',
            name='tiempo_planificado_sprint',
            field=models.PositiveIntegerField(default=1, verbose_name='tiempo planificado para el sprint'),
        ),
    ]
