# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0060_userstorysprint_tiempo_planificado_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horasTrabajadas',
            field=models.PositiveIntegerField(default=1, verbose_name='horas trabajadas'),
        ),
        migrations.AlterField(
            model_name='userstorysprint',
            name='tiempo_planificado_sprint',
            field=models.PositiveIntegerField(default=1, help_text='Especifique cuántas horas de trabajo se le dedicará al user story en este sprint.', validators=[proyecto.models.validar_mayor_a_cero], verbose_name='Tiempo Planificado'),
        ),
    ]
