# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-14 23:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0061_auto_20190613_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='es_rechazado',
            field=models.BooleanField(default=False, help_text='Indica si una actividad se realizo antes de ser rechazada'),
        ),
        migrations.AlterField(
            model_name='miembrosprint',
            name='horasAsignadas',
            field=models.PositiveIntegerField(validators=[proyecto.models.validar_mayor_a_cero, django.core.validators.MaxValueValidator(24)], verbose_name='Horas por día asignadas al miembro'),
        ),
    ]
